---
- name: Configurar interface ALSA Loopback
  lineinfile:
    dest: /etc/modprobe.d/alsa-loopback.conf
    state: "present"
    regexp: "^options snd-aloop enable=1,1,1,1,1 index=0,1,2,3,4"
    line: "options snd-aloop enable=1,1,1,1,1 index=0,1,2,3,4"
    create: yes

- name: caregar módulo kernel do snd-aloop
  modprobe:
    name: snd-aloop
    state: present


- name: "Criar pasta de instalação e config {{ JVB_INSTAL_PASTA }}/{{ JVB_CONFIG_PASTA }}"
  file:
    path: "{{ JVB_INSTAL_PASTA }}/{{ JVB_CONFIG_PASTA }}"
    state: directory
    recurse: yes

- name: Copiar compose file
  template:
    src: opt/jvb-{{ IMAGEM_TAG }}/docker-compose.yml
    dest: "{{ JVB_INSTAL_PASTA }}/docker-compose.yml"
- name: Subir stack do compose
  docker_compose:
    project_src: "{{ JVB_INSTAL_PASTA }}/docker-compose.yml"
  register: docker_compose_output
# - name: Checar Status do container
#   command: 'docker container inspect -f {{.State.Running}}' chama-jvb
#   register: container_status
#
# - name: Iniciar stack docker
#   command: docker-compose up -d
#   args:
#     chdir: "{{ JVB_INSTAL_PASTA }}/"
#   when: container_status.stdout != true
