---
- name: Configurar interface ALSA Loopback
  lineinfile:
    dest: /etc/modprobe.d/alsa-loopback.conf
    state: "present"
    regexp: "^options snd-aloop enable=1,1,1,1,1 index=0,1,2,3,4"
    line: "options snd-aloop enable=1,1,1,1,1 index=0,1,2,3,4"
    create: yes

- name: caregar módulo kernel do snd-aloop
  modprobe:
    name: snd-aloop
    state: present


- name: "Criar pasta de instalação {{ CONFIG }}"
  file:
    path: "{{ CONFIG }}"
    state: directory

- name: Copiar compose file
  template:
    src: opt/jvb/docker-compose.yml
    dest: "{{ CONFIG }}/docker-compose.yml"
