---
- name: Configurar interface ALSA Loopback
  lineinfile:
    dest: /etc/modprobe.d/alsa-loopback.conf
    state: "present"
    regexp: "^options snd-aloop enable=1,1,1,1,1 index=0,1,2,3,4"
    line: "options snd-aloop enable=1,1,1,1,1 index=0,1,2,3,4"
    create: yes

- name: caregar módulo kernel do snd-aloop
  modprobe:
    name: snd-aloop
    state: present

- name: "Criar pasta de instalação e config {{ JVB_INSTAL_PASTA }}/{{ JVB_CONFIG_PASTA }}"
  file:
    path: "{{ JVB_INSTAL_PASTA }}/{{ JVB_CONFIG_PASTA }}"
    state: directory
    recurse: yes

- name: Copiar compose file
  template:
    src: opt/jitsi/jvb/docker-compose.yml
    dest: "{{ JVB_INSTAL_PASTA }}/docker-compose.yml"
  register: compose_file_status

- name: Copiar arquivo customizado para octo no jvb interno
  template:
    src: opt/jitsi/jvb/config/custom-sip-communicator.properties
    dest: "{{ JVB_INSTAL_PASTA }}/{{ JVB_CONFIG_PASTA }}"

- name: Compose file mudou. Reconstruindo o stack
  shell: |
    docker-compose stop
    docker-compose rm -f
    docker-compose up -d
  args:
    chdir: "{{ JVB_INSTAL_PASTA }}/"
  when: compose_file_status.changed

- name: Reiniciar o jvb para aparecer o relayID no Jicofo
  shell: |
    sleep 10
    docker-compose restart

