---
- name: Instalar pacotes em debian like
  package:
    name: "{{ pacotes_deb }}"
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Instalar pacotes em Centos
  package:
    name: "{{ pacotes_centos }}"
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat
